name: poli_calc
description: Calculadora para PoliAlumnos

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.0.0-nullsafety.2

  numberpicker: ^2.0.0
  
  url_launcher: ^6.0.2

  font_awesome_flutter: ^9.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true